version: '3'

volumes:
        pg_data: {}
        feedvol: {}
        static: {}

services:

        web:
                build: web/
                container_name: feed-django
                expose:
                        - "8080"
                depends_on:
                        - db
                volumes:
                        - .:/code
                        - feedvol:/opt/feed
                        - static:/opt/feed/static
                env_file: .env
                restart: always

        db:
                image: mdillon/postgis
                container_name: feed-postgis
                ports:
                        - "5432:5432"
                volumes:
                        - pg_data:/var/lib/postgresql
                env_file: .env

        nginx:
                build: nginx/
                container_name: feed-nginx
                ports: 
                        - "80:80"
                volumes:
                        - static:/opt/feed/static
                depends_on:
                        - web
