version: '3'

volumes:
        pg_data: {}
        static: {}

services:

        web:
                build: .
                container_name: feed-django
                ports:
                        - "8080:8080"
                depends_on:
                        - db
                volumes:
                        - static:/opt/feed/static
                env_file: .env

        db:
                image: mdillon/postgis
                container_name: feed-postgis
                ports:
                        - "5432:5432"
                volumes:
                        - pg_data:/var/lib/postgresql
                env_file: .env
